name: sampleproj-workflow
on:
  push:
    branches:
      - 'develop'
      - 'feature/**'
      - 'release/**'
  pull_request:
    branches:
      - 'feature/**'
    types:
      - closed
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4
      - name: setup java
        uses: actions/setup-java@v4
        with:
          distribution: 'oracle'
          java-version: '17'
      - name: build project
        run: ./gradlew build
      - name: upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: jar-file
          path: build/libs/sampleproj.jar
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: download artifact
        uses: actions/download-artifact@v4
        with:
          name: jar-file
      - name: show content
        run: ls -al
      - name: Application Deployed
        run: echo "${{toJson(github.event)}}"