name: sampleproj-workflow
on:
  push:
    branches:
      - 'develop'
      - 'feature/**'
      - 'release/**'
  pull_request:
    branches:
      - 'feature/**'
    types:
      - closed
  workflow_dispatch:
env:
  SAMPLE_ENV_VALUE1: sample_env1
jobs:
  build:
    env:
      SAMPLE_ENV_VALUE2: sample_env2
    runs-on: ubuntu-latest
    outputs:
      publish-file: ${{steps.publish-output.outputs.publish-file}}
    steps:
      - name: checkout code
        uses: actions/checkout@v4
      - name: setup java
        uses: actions/setup-java@v4
        with:
          distribution: 'oracle'
          java-version: '17'
      - name: cache dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: build project
        run: ./gradlew build
      - name: upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: jar-file
          path: build/libs/sampleproj-0.1.jar
      - name: publish output
        id: publish-output
        run: find build/libs/*0.1.jar -type f -execdir echo 'publish-file={}' >> $GITHUB_OUTPUT ';'
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: download artifact
        uses: actions/download-artifact@v4
        with:
          name: jar-file
      - name: show content
        run: ls -al
      - name: show build output
        run: echo ${{needs.build.outputs.publish-file}}
      - name: Application Deployed
        run: echo "${{toJson(github.event)}}"